/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InpisView;

import javax.swing.JOptionPane;
import InpisController.ControlMaster;
import InpisModel.Personil;
import java.text.DateFormat;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author amazingharry95
 */
public class UI_Edit_Personil extends javax.swing.JFrame {
    UI_Edit_Istri jtRowDataIstri = new UI_Edit_Istri();
    UI_Edit_Anak rowAnak= new UI_Edit_Anak(); 
    List<String> Anak;
    String NRP;

    /**
     * Creates new form UI_Edit_Personil
     */
    public UI_Edit_Personil(){
        initComponents();
    }
    
    public UI_Edit_Personil(String nrp) {
        initComponents();
        getAllAnak(nrp);
        this.NRP = nrp;
        //cekPasangan();
    }
    
    ControlMaster controlMaster = new ControlMaster();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField23 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField_Nama = new javax.swing.JTextField();
        jTextField_Pangkat = new javax.swing.JTextField();
        jTextField_Korps = new javax.swing.JTextField();
        jTextField_NRP = new javax.swing.JTextField();
        jTextField_Jabatan = new javax.swing.JTextField();
        jTextField_TempatLahir = new javax.swing.JTextField();
        jTextField_PendidikanUmum = new javax.swing.JTextField();
        jTextField_PendidikanMiliter = new javax.swing.JTextField();
        jTextField_Agama = new javax.swing.JTextField();
        jTextField_GolonganDarah = new javax.swing.JTextField();
        jTextField_NoKTA = new javax.swing.JTextField();
        jTextField_NoASABRI = new javax.swing.JTextField();
        jTextField_NoBPJS = new javax.swing.JTextField();
        jTextField_NoNPWP = new javax.swing.JTextField();
        jTextField_Alamat = new javax.swing.JTextField();
        jTextField_StatusRumah = new javax.swing.JTextField();
        jTextField_NoTelpon = new javax.swing.JTextField();
        jTextField_StatusKeluarga = new javax.swing.JTextField();
        jTextField_Istri = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        lihatIstri = new javax.swing.JButton();
        buttonSimpan = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jTextField_PendidikanPengembang = new javax.swing.JTextField();
        jDateChooser_tanggalLahir = new com.toedter.calendar.JDateChooser();
        jabatan = new com.toedter.calendar.JDateChooser();
        tmttni = new com.toedter.calendar.JDateChooser();
        pangkatpertama = new com.toedter.calendar.JDateChooser();
        pangkatterakhir = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAnak = new javax.swing.JTable();

        jTextField23.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("EDIT PERSONIL");

        jLabel2.setText("NAMA");

        jLabel3.setText("PANGKAT");

        jLabel4.setText("KORPS");

        jLabel5.setText("NRP");

        jLabel6.setText("JABATAN");

        jLabel7.setText("TMT JABATAN");

        jLabel8.setText("TMT TNI");

        jLabel9.setText("TMT PANGKAT PERTAMA");

        jLabel10.setText("TMT PANGKAT TERAKHIR");

        jLabel11.setText("TEMPAT LAHIR");

        jLabel12.setText("TANGGAL LAHIR");

        jLabel13.setText("PENDIDIKAN UMUM");

        jLabel14.setText("PENDIDIKAN MILITER");

        jLabel15.setText("AGAMA");

        jLabel16.setText("GOLONGAN DARAH");

        jLabel17.setText("NOMOR KTA");

        jLabel18.setText("NOMOR ASABRI");

        jLabel19.setText("NOMOR BPJS");

        jLabel20.setText("NOMOR NPWP");

        jLabel21.setText("ALAMAT");

        jLabel22.setText("STATUS RUMAH");

        jLabel23.setText("NOMOR TELPON");

        jLabel24.setText("STATUS KELUARGA");

        jLabel25.setText("NAMA ISTRI");

        jTextField_Istri.setEditable(false);

        jButton2.setText("TAMBAH ANAK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonDelete.setBackground(new java.awt.Color(255, 0, 51));
        buttonDelete.setText("DELETE");
        buttonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDeleteMouseClicked(evt);
            }
        });
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        lihatIstri.setText("LIHAT PASANGAN");
        lihatIstri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatIstriActionPerformed(evt);
            }
        });

        buttonSimpan.setText("SIMPAN");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        jLabel27.setText("PENDIDIKAN PENGEMBANG");

        tableAnak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAnak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAnakMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAnak);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(92, 92, 92)
                            .addComponent(jDateChooser_tanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel1)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_TempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pangkatterakhir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pangkatpertama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tmttni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jabatan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonDelete, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Nama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(jTextField_Pangkat, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Korps, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_NRP, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Jabatan, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 22, Short.MAX_VALUE)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_PendidikanMiliter, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_PendidikanUmum, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Agama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_GolonganDarah, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_NoKTA, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_NoASABRI, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_NoBPJS, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_NoNPWP, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_StatusRumah, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_NoTelpon, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_PendidikanPengembang, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonSimpan)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lihatIstri)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_StatusKeluarga, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(jTextField_Istri))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buttonDelete))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel13)
                    .addComponent(jLabel24)
                    .addComponent(jTextField_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PendidikanUmum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_StatusKeluarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel14)
                            .addComponent(jLabel25)
                            .addComponent(jTextField_Pangkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_PendidikanMiliter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField_Istri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(jTextField_Agama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_GolonganDarah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jTextField_NoKTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_PendidikanPengembang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField_Korps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_NRP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField_Jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel18)
                                .addComponent(jTextField_NoASABRI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel19)
                        .addComponent(jTextField_NoBPJS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tmttni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel20)
                        .addComponent(jTextField_NoNPWP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lihatIstri)
                        .addComponent(jButton2))
                    .addComponent(pangkatpertama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_StatusRumah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pangkatterakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField_TempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel22))))
                            .addComponent(jLabel21))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jDateChooser_tanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(jTextField_NoTelpon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String nrp = jTextField_NRP.getText();
        
        /*if(controlMaster.punyaAnak(nrp)){
            try{

               List<String> Anak = controlMaster.ambilDataAnaklbyID(nrp);
               SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
               String dateAnak = Anak.get(4);
               Date tanggalLahirAnak = formatter.parse(dateAnak);

               this.rowAnak.setVisible(true);
               this.rowAnak.pack();
               this.rowAnak.TF_ID_Anak.setText(Anak.get(0));
               this.rowAnak.tf_nrp_anak.setText(Anak.get(1));
               this.rowAnak.TF_Nama_Anak.setText(Anak.get(2));
               this.rowAnak.date_anak.setDate(tanggalLahirAnak);
               this.rowAnak.tf_ttl_anak.setText(Anak.get(3));
                }catch(Exception e){

            }
        }else{*/
           UI_Insert_Anak uiInsertAnak = new UI_Insert_Anak(nrp);
            uiInsertAnak.setVisible(true);
 
            //uiInsertAnak.setVisible(true);
            //uiInsertAna
        //}
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDeleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDeleteMouseClicked

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus", "Hapus Personil", JOptionPane.YES_NO_OPTION);
        
        if(p==0){
            if(this.controlMaster.deletePersonil(jTextField_NRP.getText()))
                JOptionPane.showMessageDialog(null, "Terhapus");
        }
        this.dispose();
    }//GEN-LAST:event_buttonDeleteActionPerformed

    public void cekPasangan(String nrp){
        //System.out.println("masuk sini");
        
        if(controlMaster.punyaIstri(nrp)==false){
            System.out.println("masuk sini");
            lihatIstri.setText("Tambah Pasangan");
        }
    }
    
    public void cekAnak(String nrp){
        if(controlMaster.punyaAnak(nrp)==false){
            jButton2.setText("Tambah Anak");
        }
    }
    
    public void getAllAnak(String nrp){
        System.out.println("NRP di anak: "+ jTextField_NRP.getText());
        tableAnak.setModel(DbUtils.resultSetToTableModel(controlMaster.getAllAnak(nrp)));
    }
    private void lihatIstriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatIstriActionPerformed
        // TODO add your handling code here:
        String nrp = jTextField_NRP.getText();
        if(controlMaster.punyaIstri(nrp)){
            try{

               List<String> Istri = controlMaster.ambilDataIstrilbyID(nrp);
               //String lahirIstri = Istri.get(4);
               SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
               String dateIstri = Istri.get(4);
               Date tanggalLahirIstri = formatter.parse(dateIstri);
               //java.util.Date lahirIstriTanggal = new SimpleDateFormat("dd-MM-yyyy").parse(lahirIstri);
               //DateFormat lahirIstriDate = new SimpleDateFormat("dd-MM-yyyy", Locale.ENGLISH);
               //Date lahirIstriTanggal = lahirIstriDate.parse(lahirIstri);

               this.jtRowDataIstri.setVisible(true);
               this.jtRowDataIstri.pack();
               this.jtRowDataIstri.TextField_nrp_istri.setText(Istri.get(1));
               this.jtRowDataIstri.TextField_nama_istri.setText(Istri.get(2));
               this.jtRowDataIstri.TextField_ttl_istri.setText(Istri.get(3));
               this.jtRowDataIstri.date_tglLahirIstri.setDate(tanggalLahirIstri);
               this.jtRowDataIstri.TextField_agama_istri.setText(Istri.get(5));
               this.jtRowDataIstri.TextField_gol_darah_istri.setText(Istri.get(6));
               this.jtRowDataIstri.TextField_kpi_istri.setText(Istri.get(7));
               this.jtRowDataIstri.TextField_kta_istri.setText(Istri.get(8));
               this.jtRowDataIstri.TextField_kb_istri.setText(Istri.get(9));
               this.jtRowDataIstri.TextField_pendidikan_terakhir_istri.setText(Istri.get(10));
               this.jtRowDataIstri.TextField_hobby_istri.setText(Istri.get(11));
               this.jtRowDataIstri.hobi_2.setText(Istri.get(12));
                }catch(Exception e){

            }
        }else{
            UI_Insert_Istri uiInsertIstri = new UI_Insert_Istri(nrp);
            uiInsertIstri.setVisible(true);
            //uiInsertIstri
            //jtRowDataIstri.setVisible(true);
            //jtRowDataIstri.TextField_nrp_istri.setText(nrp);
        }
    }//GEN-LAST:event_lihatIstriActionPerformed

    
    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        Format formatter = new SimpleDateFormat("dd-MM-yyyy");
        Date tanggalLahirPersonil = this.jDateChooser_tanggalLahir.getDate();
        String tanggalLahir = formatter.format(tanggalLahirPersonil);
        
        Date tmtjabatan = this.jabatan.getDate();
        String tmtJabatan = formatter.format(tmtjabatan);
        Date tmttni = this.tmttni.getDate();
        String tmtTNI = formatter.format(tmttni);
        Date pertama = this.pangkatpertama.getDate();
        String tmtpertama = formatter.format(pertama);
        Date terakhir = this.pangkatterakhir.getDate();
        String tmtterakhir = formatter.format(terakhir);

        
        String nrp = jTextField_NRP.getText();
        String agama = this.jTextField_Agama.getText();
        String golDarah = this.jTextField_GolonganDarah.getText();
        String jabatan = this.jTextField_Jabatan.getText();
        String korps = this.jTextField_Korps.getText();
        String nama = this.jTextField_Nama.getText();
        String noASABRI = this.jTextField_NoASABRI.getText();
        String noBPJS = this.jTextField_NoBPJS.getText();
        String noKTA = this.jTextField_NoKTA.getText();
        String noNPWP = this.jTextField_NoNPWP.getText();
        String noTelpon = this.jTextField_NoTelpon.getText();
        String pangkat = this.jTextField_Pangkat.getText();
        String penMiliter = this.jTextField_PendidikanMiliter.getText();
        String penPengembang = this.jTextField_PendidikanPengembang.getText();
        String penUmum = this.jTextField_PendidikanUmum.getText();
        String statusKeluarga = this.jTextField_StatusKeluarga.getText();
        String statusRumah = this.jTextField_StatusRumah.getText();
        //String tmtTNI = this.jTextField_TamatTNI.getText();
        String tmptLahir = this.jTextField_TempatLahir.getText();    
        //String tmtPangkatPertama = this.jTextField_TamatPangkatPertama.getText();
        //String tmtPangkatTerakhir = this.jTextField_TamatPangkatTerakhir.getText();
        String alamat = this.jTextField_Alamat.getText();
        
        int p = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menyimpan edit", "Edit Personil", JOptionPane.YES_NO_OPTION);
        
        if(p==0){
            if(this.controlMaster.updatePersonil(nrp, agama, golDarah, jabatan, korps, nama, noASABRI, noBPJS, noKTA, noNPWP, noTelpon, pangkat, penMiliter, penPengembang, penUmum, statusKeluarga, statusRumah, tmtJabatan, tmtTNI, tanggalLahir, tmptLahir, tmtpertama, tmtterakhir, alamat)==1)
                JOptionPane.showMessageDialog(null, "Berhasil Edit");
        }
        this.dispose();
        new UI_Utama_v2().getAllData();
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private List<String> ambilDataAnak(String ID){
        return new ControlMaster().getAnakbyID(ID);
    }
    private void tableAnakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAnakMouseClicked
        // TODO add your handling code here:
        try{
            if(evt.getClickCount()==1){
                int row = tableAnak.getSelectedRow();
                String table_click = (tableAnak.getModel().getValueAt(row, 0).toString());
                Anak = this.ambilDataAnak(table_click);
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                String tanggalLahirAnak = Anak.get(4);
                Date bornDateAnak = formatter.parse(tanggalLahirAnak);
                
                UI_Edit_Anak uiEditAnak = new UI_Edit_Anak();
                uiEditAnak.setVisible(true);
                uiEditAnak.pack();
                
                uiEditAnak.TF_ID_Anak.setText(Anak.get(0));
                uiEditAnak.TF_Nama_Anak.setText(Anak.get(2));
                uiEditAnak.tf_nrp_anak.setText(Anak.get(1));
                uiEditAnak.tf_ttl_anak.setText(Anak.get(3));
                uiEditAnak.date_anak.setDate(bornDateAnak);
                

                //System.out.println("Nrp di anak: "+ this.NRP);
                //System.out.println("Click di anak:"+table_click);
        }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_tableAnakMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Edit_Personil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Edit_Personil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Edit_Personil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Edit_Personil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Edit_Personil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton jButton2;
    public com.toedter.calendar.JDateChooser jDateChooser_tanggalLahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField23;
    public javax.swing.JTextField jTextField_Agama;
    public javax.swing.JTextField jTextField_Alamat;
    public javax.swing.JTextField jTextField_GolonganDarah;
    public javax.swing.JTextField jTextField_Istri;
    public javax.swing.JTextField jTextField_Jabatan;
    public javax.swing.JTextField jTextField_Korps;
    public javax.swing.JTextField jTextField_NRP;
    public javax.swing.JTextField jTextField_Nama;
    public javax.swing.JTextField jTextField_NoASABRI;
    public javax.swing.JTextField jTextField_NoBPJS;
    public javax.swing.JTextField jTextField_NoKTA;
    public javax.swing.JTextField jTextField_NoNPWP;
    public javax.swing.JTextField jTextField_NoTelpon;
    public javax.swing.JTextField jTextField_Pangkat;
    public javax.swing.JTextField jTextField_PendidikanMiliter;
    public javax.swing.JTextField jTextField_PendidikanPengembang;
    public javax.swing.JTextField jTextField_PendidikanUmum;
    public javax.swing.JTextField jTextField_StatusKeluarga;
    public javax.swing.JTextField jTextField_StatusRumah;
    public javax.swing.JTextField jTextField_TempatLahir;
    public com.toedter.calendar.JDateChooser jabatan;
    private javax.swing.JButton lihatIstri;
    public com.toedter.calendar.JDateChooser pangkatpertama;
    public com.toedter.calendar.JDateChooser pangkatterakhir;
    private javax.swing.JTable tableAnak;
    public com.toedter.calendar.JDateChooser tmttni;
    // End of variables declaration//GEN-END:variables
}
