/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InpisView;

import InpisController.ControlMaster;
import java.util.Date;

/**
 *
 * @author USER
 */
public class UI_Insert_Istri extends javax.swing.JFrame {

    ControlMaster controlMaster = new ControlMaster();
    /**
     * Creates new form UI_INSERT_ISTRI
     */
    public UI_Insert_Istri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_insert_istri = new javax.swing.JLabel();
        label_nama_istri = new javax.swing.JLabel();
        label_nrp_istri = new javax.swing.JLabel();
        label_agama_istri = new javax.swing.JLabel();
        label_gol_darah_istri = new javax.swing.JLabel();
        label_kpi_istri = new javax.swing.JLabel();
        label_kta_istri = new javax.swing.JLabel();
        label_kb_istri = new javax.swing.JLabel();
        label_pendidikan_terakhir_istri = new javax.swing.JLabel();
        label_tmptlahir_istri = new javax.swing.JLabel();
        button_simpan_insert_istri = new javax.swing.JButton();
        txt_namaIstri = new javax.swing.JTextField();
        txt_NRP = new javax.swing.JTextField();
        txt_KPIIstri = new javax.swing.JTextField();
        txt_KTAJalasenastri = new javax.swing.JTextField();
        txt_penTerakhirIstri = new javax.swing.JTextField();
        txt_tmptLahirIstri = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        date_tglLahirIstri = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_hobi1 = new javax.swing.JTextField();
        txt_hobi2 = new javax.swing.JTextField();
        combo_agamaIstri = new javax.swing.JComboBox<>();
        combo_golDarahIstri = new javax.swing.JComboBox<>();
        combo_metodeKB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(360, 112));

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 510));

        label_insert_istri.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        label_insert_istri.setText("DATA PASANGAN");
        label_insert_istri.setMaximumSize(new java.awt.Dimension(262, 44));
        label_insert_istri.setMinimumSize(new java.awt.Dimension(262, 44));
        label_insert_istri.setPreferredSize(new java.awt.Dimension(262, 44));

        label_nama_istri.setText("Nama Pasangan :");

        label_nrp_istri.setText("NRP :");

        label_agama_istri.setText("Agama Pasangan :");

        label_gol_darah_istri.setText("Golongan Darah Pasangan :");

        label_kpi_istri.setText("KPI Pasangan :");

        label_kta_istri.setText("KTA Jalasenastri :");

        label_kb_istri.setText("Metode KB :");

        label_pendidikan_terakhir_istri.setText("Pendidikan Terakhir Pasangan :");

        label_tmptlahir_istri.setText("Tempat Lahir Pasangan :");

        button_simpan_insert_istri.setText("Simpan");
        button_simpan_insert_istri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_simpan_insert_istriActionPerformed(evt);
            }
        });

        txt_NRP.setEditable(false);

        jLabel1.setText("Tanggal Lahir Pasangan :");

        jLabel2.setText("Hobi 1 :");

        jLabel3.setText("Hobi 2 :");

        combo_agamaIstri.setEditable(true);
        combo_agamaIstri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Islam", "Kristen", "Katolik", "Hindu", "Budha" }));
        combo_agamaIstri.setSelectedIndex(-1);

        combo_golDarahIstri.setEditable(true);
        combo_golDarahIstri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "A", "B", "AB", "O", " " }));
        combo_golDarahIstri.setSelectedIndex(-1);

        combo_metodeKB.setEditable(true);
        combo_metodeKB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IUP", "PIL", "SUNIK", "WOW", "MOP", "KONDOM", "SUSUK", "SPIRAL" }));
        combo_metodeKB.setSelectedIndex(-1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_hobi1)
                                    .addComponent(txt_hobi2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_pendidikan_terakhir_istri)
                                    .addComponent(label_kta_istri)
                                    .addComponent(label_kpi_istri)
                                    .addComponent(label_gol_darah_istri)
                                    .addComponent(label_agama_istri)
                                    .addComponent(label_kb_istri)
                                    .addComponent(label_tmptlahir_istri)
                                    .addComponent(label_nama_istri)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_penTerakhirIstri, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(date_tglLahirIstri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txt_tmptLahirIstri, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_KTAJalasenastri, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_KPIIstri, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_namaIstri, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_NRP, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(combo_agamaIstri, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combo_golDarahIstri, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combo_metodeKB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(button_simpan_insert_istri)))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nrp_istri)
                            .addComponent(label_insert_istri, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(label_insert_istri, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nrp_istri)
                    .addComponent(txt_NRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_namaIstri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama_istri))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_agama_istri)
                    .addComponent(combo_agamaIstri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_gol_darah_istri)
                    .addComponent(combo_golDarahIstri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_kpi_istri)
                    .addComponent(txt_KPIIstri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_kta_istri)
                    .addComponent(txt_KTAJalasenastri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_kb_istri)
                    .addComponent(combo_metodeKB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_pendidikan_terakhir_istri)
                    .addComponent(txt_penTerakhirIstri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tmptlahir_istri)
                    .addComponent(txt_tmptLahirIstri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(date_tglLahirIstri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_hobi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_hobi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(button_simpan_insert_istri)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_simpan_insert_istriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_simpan_insert_istriActionPerformed
        String KPIIstri = txt_KPIIstri.getText();
        String KTAJalasenastri = txt_KTAJalasenastri.getText();
        String NRP = txt_NRP.getText();
        String agamaIstri = combo_agamaIstri.getSelectedItem().toString();
        String golDarahIstri = combo_golDarahIstri.getSelectedItem().toString();
        String hobi1 = txt_hobi1.getText();
        String hobi2 = txt_hobi2.getText();
        String metodeKb = combo_metodeKB.getSelectedItem().toString();
        String namaIstri = txt_namaIstri.getText();
        String penTerakhirIstri = txt_penTerakhirIstri.getText();
        String tmptLahirIstri = txt_tmptLahirIstri.getText();
//        DateFormat fmt = new SimpleDateFormat("dd MMMM yyyy");
//        String tglLahirIstri = fmt.format(this.date_tglLahirIstri.getDate());
        Date tglLahirIstri = date_tglLahirIstri.getDate();
        
        controlMaster.InsertIstriData(NRP, agamaIstri, golDarahIstri, KPIIstri, KTAJalasenastri, 
                metodeKb, penTerakhirIstri, tmptLahirIstri, namaIstri, tglLahirIstri, hobi1, hobi2);
        this.dispose();
    }//GEN-LAST:event_button_simpan_insert_istriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Insert_Istri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Insert_Istri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Insert_Istri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Insert_Istri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UI_Insert_Istri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_simpan_insert_istri;
    private javax.swing.JComboBox<String> combo_agamaIstri;
    private javax.swing.JComboBox<String> combo_golDarahIstri;
    private javax.swing.JComboBox<String> combo_metodeKB;
    private com.toedter.calendar.JDateChooser date_tglLahirIstri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_agama_istri;
    private javax.swing.JLabel label_gol_darah_istri;
    private javax.swing.JLabel label_insert_istri;
    private javax.swing.JLabel label_kb_istri;
    private javax.swing.JLabel label_kpi_istri;
    private javax.swing.JLabel label_kta_istri;
    private javax.swing.JLabel label_nama_istri;
    private javax.swing.JLabel label_nrp_istri;
    private javax.swing.JLabel label_pendidikan_terakhir_istri;
    private javax.swing.JLabel label_tmptlahir_istri;
    private javax.swing.JTextField txt_KPIIstri;
    private javax.swing.JTextField txt_KTAJalasenastri;
    public static javax.swing.JTextField txt_NRP;
    private javax.swing.JTextField txt_hobi1;
    private javax.swing.JTextField txt_hobi2;
    private javax.swing.JTextField txt_namaIstri;
    private javax.swing.JTextField txt_penTerakhirIstri;
    private javax.swing.JTextField txt_tmptLahirIstri;
    // End of variables declaration//GEN-END:variables
}
