/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InpisView;

import InpisController.ControlMaster;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class UI_Insert_Personil extends javax.swing.JFrame {

    /**
     * Creates new form UI_Insert_Personil
     */
    
    ControlMaster controlMaster = new ControlMaster();
    
    public UI_Insert_Personil() {
        initComponents();
    }

//    private void InsertPersonilData(String NRP, String agamaPersonil, String golDarahPersonil, String jabatan, 
//            String korps, String namaPersonil, String noASABRI, String noBPJS, String noKTA, String noNPWP, 
//            String noTelepon, String pangkat, String penMiliter, String penPengembang, String penUmum, 
//            String statusKeluarga, String statusRumah, String tamatJabatan, String tamatTNI, String tglLahirPersonil, 
//            String tmptLahirPersonil, String tmtPangkatPertama, String tmtPangkatTerakhir, String alamatPersonil) {
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnInsertPersonil = new javax.swing.JButton();
        button_insert_tambah_istri = new javax.swing.JButton();
        button_insert_tambah_anak = new javax.swing.JButton();
        txt_namaPersonil = new javax.swing.JTextField();
        txt_noASABRI = new javax.swing.JTextField();
        txt_NRPPersonil = new javax.swing.JTextField();
        txt_noBPJS = new javax.swing.JTextField();
        txt_noKTA = new javax.swing.JTextField();
        txt_noNPWP = new javax.swing.JTextField();
        txt_noTelepon = new javax.swing.JTextField();
        txt_agamaPersonil = new javax.swing.JTextField();
        txt_alamatPersonil = new javax.swing.JTextField();
        txt_golDarahPersonil = new javax.swing.JTextField();
        txt_jabatan = new javax.swing.JTextField();
        txt_korps = new javax.swing.JTextField();
        txt_pangkat = new javax.swing.JTextField();
        txt_pendidikanMiliter = new javax.swing.JTextField();
        txt_pendidikanPengembang = new javax.swing.JTextField();
        txt_pendidikanUmum = new javax.swing.JTextField();
        txt_statusKeluarga = new javax.swing.JTextField();
        txt_statusRumah = new javax.swing.JTextField();
        txt_tempatLahirPersonil = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        date_tamatJabatan = new com.toedter.calendar.JDateChooser();
        date_tamatTNI = new com.toedter.calendar.JDateChooser();
        date_tanggalLahirPersonil = new com.toedter.calendar.JDateChooser();
        date_TMTPangkatPertama = new com.toedter.calendar.JDateChooser();
        date_TMTPangkatTerakhir = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(460, 1100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("DATA PERSONIL");

        jLabel2.setText("Nama Personil :");

        jLabel3.setText("NRP :");

        jLabel4.setText("No. ASABRI :");

        jLabel5.setText("No. BPJS :");

        jLabel6.setText("No. KTA :");

        jLabel7.setText("No. NPWP :");

        jLabel8.setText("No. Telepon :");

        jLabel9.setText("Agama Personil :");

        jLabel10.setText("Alamat Personil :");

        jLabel11.setText("Golongan Darah Personil :");

        jLabel12.setText("Jabatan :");

        jLabel13.setText("Korps :");

        jLabel14.setText("Pangkat :");

        jLabel16.setText("Pendidikan Pengembang :");

        jLabel17.setText("Pendidikan Umum :");

        jLabel18.setText("Status Keluarga :");

        jLabel19.setText("Status Rumah :");

        jLabel20.setText("Tamat Jabatan :");

        jLabel21.setText("Tamat TNI :");

        jLabel22.setText("Tempat Lahir Personil :");

        jLabel23.setText("TMT Pangkat Pertama :");

        jLabel24.setText("TMT Pangkat Terakhir :");

        jLabel25.setText("Pendidikan Militer :");

        btnInsertPersonil.setText("Simpan");
        btnInsertPersonil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertPersonilActionPerformed(evt);
            }
        });

        button_insert_tambah_istri.setText("Tambah Data Istri");
        button_insert_tambah_istri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_insert_tambah_istriActionPerformed(evt);
            }
        });

        button_insert_tambah_anak.setText("Tambah Data Anak");
        button_insert_tambah_anak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_insert_tambah_anakActionPerformed(evt);
            }
        });

        txt_namaPersonil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaPersonilActionPerformed(evt);
            }
        });

        txt_noASABRI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noASABRIActionPerformed(evt);
            }
        });

        txt_NRPPersonil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NRPPersonilActionPerformed(evt);
            }
        });

        txt_noBPJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noBPJSActionPerformed(evt);
            }
        });

        txt_noKTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noKTAActionPerformed(evt);
            }
        });

        txt_noNPWP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noNPWPActionPerformed(evt);
            }
        });

        txt_noTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noTeleponActionPerformed(evt);
            }
        });

        txt_agamaPersonil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_agamaPersonilActionPerformed(evt);
            }
        });

        txt_alamatPersonil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatPersonilActionPerformed(evt);
            }
        });

        txt_golDarahPersonil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_golDarahPersonilActionPerformed(evt);
            }
        });

        txt_jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jabatanActionPerformed(evt);
            }
        });

        txt_korps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_korpsActionPerformed(evt);
            }
        });

        txt_pangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pangkatActionPerformed(evt);
            }
        });

        txt_pendidikanMiliter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pendidikanMiliterActionPerformed(evt);
            }
        });

        txt_pendidikanPengembang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pendidikanPengembangActionPerformed(evt);
            }
        });

        txt_pendidikanUmum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pendidikanUmumActionPerformed(evt);
            }
        });

        txt_statusKeluarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_statusKeluargaActionPerformed(evt);
            }
        });

        txt_statusRumah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_statusRumahActionPerformed(evt);
            }
        });

        txt_tempatLahirPersonil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tempatLahirPersonilActionPerformed(evt);
            }
        });

        jLabel26.setText("Tanggal Lahir Personil :");

        date_tamatJabatan.setDateFormatString("dd-MM-yyyy");

        date_tamatTNI.setDateFormatString("dd-MM-yyyy");

        date_tanggalLahirPersonil.setDateFormatString("dd MMMM yyyy");

        date_TMTPangkatPertama.setDateFormatString("dd-MM-yyyy");

        date_TMTPangkatTerakhir.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(button_insert_tambah_istri)
                                .addGap(18, 18, 18)
                                .addComponent(button_insert_tambah_anak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addComponent(btnInsertPersonil))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_NRPPersonil, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txt_noASABRI, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txt_noBPJS, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txt_noKTA, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txt_noNPWP, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txt_noTelepon, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txt_agamaPersonil, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txt_alamatPersonil, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txt_golDarahPersonil, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txt_jabatan, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txt_korps, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txt_pangkat, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txt_pendidikanUmum, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txt_pendidikanMiliter, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txt_pendidikanPengembang, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txt_statusKeluarga, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txt_statusRumah, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txt_tempatLahirPersonil, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(date_tamatJabatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(date_tamatTNI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(date_tanggalLahirPersonil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_namaPersonil, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(date_TMTPangkatPertama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(date_TMTPangkatTerakhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(35, 35, 35))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_namaPersonil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_NRPPersonil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_noASABRI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_noBPJS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_noKTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_noNPWP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_noTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_agamaPersonil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_alamatPersonil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_golDarahPersonil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_korps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_pangkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pendidikanMiliter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_pendidikanPengembang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_pendidikanUmum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_statusKeluarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_statusRumah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(date_tamatJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(date_tamatTNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_tempatLahirPersonil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26)
                    .addComponent(date_tanggalLahirPersonil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(date_TMTPangkatPertama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(date_TMTPangkatTerakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_insert_tambah_istri)
                    .addComponent(button_insert_tambah_anak)
                    .addComponent(btnInsertPersonil))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tempatLahirPersonilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tempatLahirPersonilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tempatLahirPersonilActionPerformed

    private void txt_statusRumahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_statusRumahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_statusRumahActionPerformed

    private void txt_statusKeluargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_statusKeluargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_statusKeluargaActionPerformed

    private void txt_pendidikanUmumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pendidikanUmumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pendidikanUmumActionPerformed

    private void txt_pendidikanPengembangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pendidikanPengembangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pendidikanPengembangActionPerformed

    private void txt_pendidikanMiliterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pendidikanMiliterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pendidikanMiliterActionPerformed

    private void txt_pangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pangkatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pangkatActionPerformed

    private void txt_korpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_korpsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_korpsActionPerformed

    private void txt_jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jabatanActionPerformed

    private void txt_golDarahPersonilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_golDarahPersonilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_golDarahPersonilActionPerformed

    private void txt_alamatPersonilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatPersonilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatPersonilActionPerformed

    private void txt_agamaPersonilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_agamaPersonilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_agamaPersonilActionPerformed

    private void txt_noTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noTeleponActionPerformed

    private void txt_noNPWPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noNPWPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noNPWPActionPerformed

    private void txt_noKTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noKTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noKTAActionPerformed

    private void txt_noBPJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noBPJSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noBPJSActionPerformed

    private void txt_NRPPersonilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NRPPersonilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NRPPersonilActionPerformed

    private void txt_noASABRIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noASABRIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noASABRIActionPerformed

    private void txt_namaPersonilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaPersonilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaPersonilActionPerformed

    private void button_insert_tambah_anakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_insert_tambah_anakActionPerformed
        UI_Insert_Anak ui_insert_anak = new UI_Insert_Anak();
        String NRPPersonil = txt_NRPPersonil.getText();
        try {
            if(NRPPersonil != null) {
                UI_Insert_Anak.txt_NRP.setText(txt_NRPPersonil.getText());
                ui_insert_anak.setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(null, "Pastikan NRP Personil sudah diisi dan disimpan terlebih dahulu");
        }catch(HeadlessException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_button_insert_tambah_anakActionPerformed

    private void btnInsertPersonilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertPersonilActionPerformed
        String NRP = txt_NRPPersonil.getText();
        String agamaPersonil = txt_agamaPersonil.getText();
        String golDarahPersonil = txt_golDarahPersonil.getText(); 
        String jabatan = txt_jabatan.getText();
        String korps = txt_korps.getText();
        String namaPersonil = txt_namaPersonil.getText();
        String noASABRI = txt_noASABRI.getText();
        String noBPJS = txt_noBPJS.getText();
        String noKTA = txt_noKTA.getText();
        String noNPWP = txt_noNPWP.getText();
        String noTelepon = txt_noTelepon.getText();
        String pangkat = txt_pangkat.getText();
        String penMiliter = txt_pendidikanMiliter.getText();
        String penPengembang = txt_pendidikanPengembang.getText(); 
        String penUmum = txt_pendidikanUmum.getText();
        String statusKeluarga = txt_statusKeluarga.getText();
        String statusRumah = txt_statusRumah.getText();
        Date tamatJabatan = date_tamatJabatan.getDate();
        Date tamatTNI = date_tamatTNI.getDate();
        String tmptLahirPersonil = txt_tempatLahirPersonil.getText();
        DateFormat fmt = new SimpleDateFormat("dd MMMM yyyy");
        String tglLahirPersonil= fmt.format(this.date_tanggalLahirPersonil.getDate());
        Date tmtPangkatPertama = date_TMTPangkatPertama.getDate();
        Date tmtPangkatTerakhir = date_TMTPangkatTerakhir.getDate(); 
        String alamatPersonil = txt_alamatPersonil.getText();
        
        controlMaster.InsertPersonilData(NRP, agamaPersonil, golDarahPersonil, jabatan, korps, namaPersonil, noASABRI, noBPJS, 
                noKTA, noNPWP, noTelepon, pangkat, penMiliter, penPengembang, penUmum, statusKeluarga, statusRumah,
                tamatJabatan, tamatTNI, tglLahirPersonil, tmptLahirPersonil, tmtPangkatPertama, tmtPangkatTerakhir,
                alamatPersonil);
    }//GEN-LAST:event_btnInsertPersonilActionPerformed

    private void button_insert_tambah_istriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_insert_tambah_istriActionPerformed
        String NRPPersonil = txt_NRPPersonil.getText();
        UI_Insert_Istri ui_insert_istri = new UI_Insert_Istri();

        try {
            if(NRPPersonil != null) {
                UI_Insert_Istri.txt_NRP.setText(txt_NRPPersonil.getText());
                ui_insert_istri.setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(null, "Pastikan NRP Personil sudah diisi dan disimpan terlebih dahulu");
        }catch(HeadlessException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_button_insert_tambah_istriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Insert_Personil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Insert_Personil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Insert_Personil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Insert_Personil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UI_Insert_Personil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertPersonil;
    private javax.swing.JButton button_insert_tambah_anak;
    private javax.swing.JButton button_insert_tambah_istri;
    private com.toedter.calendar.JDateChooser date_TMTPangkatPertama;
    private com.toedter.calendar.JDateChooser date_TMTPangkatTerakhir;
    private com.toedter.calendar.JDateChooser date_tamatJabatan;
    private com.toedter.calendar.JDateChooser date_tamatTNI;
    private com.toedter.calendar.JDateChooser date_tanggalLahirPersonil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txt_NRPPersonil;
    private javax.swing.JTextField txt_agamaPersonil;
    private javax.swing.JTextField txt_alamatPersonil;
    private javax.swing.JTextField txt_golDarahPersonil;
    private javax.swing.JTextField txt_jabatan;
    private javax.swing.JTextField txt_korps;
    private javax.swing.JTextField txt_namaPersonil;
    private javax.swing.JTextField txt_noASABRI;
    private javax.swing.JTextField txt_noBPJS;
    private javax.swing.JTextField txt_noKTA;
    private javax.swing.JTextField txt_noNPWP;
    private javax.swing.JTextField txt_noTelepon;
    private javax.swing.JTextField txt_pangkat;
    private javax.swing.JTextField txt_pendidikanMiliter;
    private javax.swing.JTextField txt_pendidikanPengembang;
    private javax.swing.JTextField txt_pendidikanUmum;
    private javax.swing.JTextField txt_statusKeluarga;
    private javax.swing.JTextField txt_statusRumah;
    private javax.swing.JTextField txt_tempatLahirPersonil;
    // End of variables declaration//GEN-END:variables
}
