/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InpisView;

import InpisController.ControlMaster;
import java.awt.HeadlessException;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class UI_Insert_Personil extends javax.swing.JFrame {

    /**
     * Creates new form UI_Insert_Personil
     */
    
    ControlMaster controlMaster = new ControlMaster();
    
    public UI_Insert_Personil() {
        initComponents();
    }

    
//    private void InsertPersonilData(String NRP, String agamaPersonil, String golDarahPersonil, String jabatan, 
//            String korps, String namaPersonil, String noASABRI, String noBPJS, String noKTA, String noNPWP, 
//            String noTelepon, String pangkat, String penMiliter, String penPengembang, String penUmum, 
//            String statusKeluarga, String statusRumah, String tamatJabatan, String tamatTNI, String tglLahirPersonil, 
//            String tmptLahirPersonil, String tmtPangkatPertama, String tmtPangkatTerakhir, String alamatPersonil) {
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnInsertPersonil = new javax.swing.JButton();
        button_insert_tambah_istri = new javax.swing.JButton();
        button_insert_tambah_anak = new javax.swing.JButton();
        txt_namaPersonil = new javax.swing.JTextField();
        txt_noASABRI = new javax.swing.JTextField();
        txt_NRPPersonil = new javax.swing.JTextField();
        txt_noBPJS = new javax.swing.JTextField();
        txt_noKTA = new javax.swing.JTextField();
        txt_noNPWP = new javax.swing.JTextField();
        txt_noTelepon = new javax.swing.JTextField();
        txt_alamatPersonil = new javax.swing.JTextField();
        txt_jabatan = new javax.swing.JTextField();
        txt_pendidikanPengembang = new javax.swing.JTextField();
        txt_pendidikanUmum = new javax.swing.JTextField();
        txt_statusKeluarga = new javax.swing.JTextField();
        txt_statusRumah = new javax.swing.JTextField();
        txt_tempatLahirPersonil = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        date_TMTJabatan = new com.toedter.calendar.JDateChooser();
        date_TMTTNI = new com.toedter.calendar.JDateChooser();
        date_tglLahirPersonil = new com.toedter.calendar.JDateChooser();
        date_TMTPangkatPertama = new com.toedter.calendar.JDateChooser();
        date_TMTPangkatTerakhir = new com.toedter.calendar.JDateChooser();
        combo_pangkat = new javax.swing.JComboBox<>();
        combo_golDarahPersonil = new javax.swing.JComboBox<>();
        combo_agamaPersonil = new javax.swing.JComboBox<>();
        combo_pendidikanMiliter = new javax.swing.JComboBox<>();
        combo_korps = new javax.swing.JComboBox<>();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 700));
        setResizable(false);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 700));

        jPanel1.setPreferredSize(new java.awt.Dimension(465, 900));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TAMBAH DATA PERSONIL");

        jLabel2.setText("Nama Personil :");

        jLabel3.setText("NRP :");

        jLabel4.setText("No. ASABRI :");

        jLabel5.setText("No. BPJS :");

        jLabel6.setText("No. KTA :");

        jLabel7.setText("No. NPWP :");

        jLabel8.setText("No. Telepon :");

        jLabel9.setText("Agama Personil :");

        jLabel10.setText("Alamat Personil :");

        jLabel11.setText("Golongan Darah Personil :");

        jLabel12.setText("Jabatan :");

        jLabel13.setText("Korps :");

        jLabel14.setText("Pangkat :");

        jLabel16.setText("Pendidikan Pengembang :");

        jLabel17.setText("Pendidikan Umum :");

        jLabel18.setText("Status Keluarga :");

        jLabel19.setText("Status Rumah :");

        jLabel20.setText("TMT Jabatan :");

        jLabel21.setText("TMT TNI :");

        jLabel22.setText("Tempat Lahir Personil :");

        jLabel23.setText("TMT Pangkat Pertama :");

        jLabel24.setText("TMT Pangkat Terakhir :");

        jLabel25.setText("Pendidikan Militer :");

        btnInsertPersonil.setText("Simpan");
        btnInsertPersonil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertPersonilActionPerformed(evt);
            }
        });

        button_insert_tambah_istri.setText("Tambah Data Suami/Istri");
        button_insert_tambah_istri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_insert_tambah_istriActionPerformed(evt);
            }
        });

        button_insert_tambah_anak.setText("Tambah Data Anak");
        button_insert_tambah_anak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_insert_tambah_anakActionPerformed(evt);
            }
        });

        txt_namaPersonil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaPersonilActionPerformed(evt);
            }
        });

        txt_noASABRI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noASABRIActionPerformed(evt);
            }
        });

        txt_NRPPersonil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NRPPersonilActionPerformed(evt);
            }
        });

        txt_noBPJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noBPJSActionPerformed(evt);
            }
        });

        txt_noKTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noKTAActionPerformed(evt);
            }
        });

        txt_noNPWP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noNPWPActionPerformed(evt);
            }
        });

        txt_noTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noTeleponActionPerformed(evt);
            }
        });

        txt_alamatPersonil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatPersonilActionPerformed(evt);
            }
        });

        txt_jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jabatanActionPerformed(evt);
            }
        });

        txt_pendidikanPengembang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pendidikanPengembangActionPerformed(evt);
            }
        });

        txt_pendidikanUmum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pendidikanUmumActionPerformed(evt);
            }
        });

        txt_statusKeluarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_statusKeluargaActionPerformed(evt);
            }
        });

        txt_statusRumah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_statusRumahActionPerformed(evt);
            }
        });

        txt_tempatLahirPersonil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tempatLahirPersonilActionPerformed(evt);
            }
        });

        jLabel26.setText("Tanggal Lahir Personil :");

        date_TMTJabatan.setDateFormatString("dd-MM-yyyy");

        date_TMTTNI.setDateFormatString("dd-MM-yyyy");

        date_tglLahirPersonil.setDateFormatString("dd MMMM yyyy");

        date_TMTPangkatPertama.setDateFormatString("dd-MM-yyyy");

        date_TMTPangkatTerakhir.setDateFormatString("dd-MM-yyyy");

        combo_pangkat.setEditable(true);
        combo_pangkat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Kolonel", "Letkol", "Mayor", "Kapten", "Lettu", "Letda", "Peltu", "Pelda", "Serma", "Serka", "Sertu", "Serda", "Kopka", "", "", "", "", "-", "Koptu", "Kopda", "Klk", "Kls", "Kld" }));

        combo_golDarahPersonil.setEditable(true);
        combo_golDarahPersonil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "-", "A", "B", "AB", "O", "" }));

        combo_agamaPersonil.setEditable(true);
        combo_agamaPersonil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "-", "Islam", "Kristen", "Katolik", "Hindu", "Budha" }));

        combo_pendidikanMiliter.setEditable(true);
        combo_pendidikanMiliter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "AAL", "SEPA PK", "Dik Tukpa Reg", "Dik Tukba Reg", "Dik Tukba", "Dik Cata" }));

        combo_korps.setEditable(true);
        combo_korps.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "-", "(P)", "(T)", "(S)", "(KH)" }));

        backButton.setText("BACK");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(backButton))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(button_insert_tambah_istri)
                            .addGap(18, 18, 18)
                            .addComponent(button_insert_tambah_anak)
                            .addGap(72, 72, 72)
                            .addComponent(btnInsertPersonil))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(72, 72, 72)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(date_TMTPangkatPertama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(date_tglLahirPersonil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                .addComponent(txt_tempatLahirPersonil, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(date_TMTTNI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(date_TMTJabatan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_statusRumah, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_statusKeluarga, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_pendidikanUmum, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_pendidikanPengembang, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(combo_pendidikanMiliter, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combo_pangkat, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combo_korps, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_jabatan, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(combo_golDarahPersonil, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_alamatPersonil, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(combo_agamaPersonil, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_noTelepon, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_noNPWP, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_noKTA, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_noBPJS, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_noASABRI, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_namaPersonil, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_NRPPersonil, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(date_TMTPangkatTerakhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_namaPersonil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_NRPPersonil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_noASABRI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_noBPJS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_noKTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_noNPWP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_noTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(combo_agamaPersonil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_alamatPersonil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(combo_golDarahPersonil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(combo_korps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(combo_pangkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(combo_pendidikanMiliter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_pendidikanPengembang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_pendidikanUmum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_statusKeluarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_statusRumah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(date_TMTJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(date_TMTTNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_tempatLahirPersonil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(date_tglLahirPersonil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date_TMTPangkatPertama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(date_TMTPangkatTerakhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_insert_tambah_istri)
                    .addComponent(button_insert_tambah_anak)
                    .addComponent(btnInsertPersonil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();

        new UI_Utama_v2().setVisible(true);
    }//GEN-LAST:event_backButtonMouseClicked

    private void txt_tempatLahirPersonilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tempatLahirPersonilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tempatLahirPersonilActionPerformed

    private void txt_statusRumahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_statusRumahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_statusRumahActionPerformed

    private void txt_statusKeluargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_statusKeluargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_statusKeluargaActionPerformed

    private void txt_pendidikanUmumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pendidikanUmumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pendidikanUmumActionPerformed

    private void txt_pendidikanPengembangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pendidikanPengembangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pendidikanPengembangActionPerformed

    private void txt_jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jabatanActionPerformed

    private void txt_alamatPersonilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatPersonilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatPersonilActionPerformed

    private void txt_noTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noTeleponActionPerformed

    private void txt_noNPWPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noNPWPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noNPWPActionPerformed

    private void txt_noKTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noKTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noKTAActionPerformed

    private void txt_noBPJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noBPJSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noBPJSActionPerformed

    private void txt_NRPPersonilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NRPPersonilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NRPPersonilActionPerformed

    private void txt_noASABRIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noASABRIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noASABRIActionPerformed

    private void txt_namaPersonilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaPersonilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaPersonilActionPerformed

    private void button_insert_tambah_anakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_insert_tambah_anakActionPerformed
        UI_Insert_Anak ui_insert_anak = new UI_Insert_Anak();
        String NRPPersonil = txt_NRPPersonil.getText();
        try {
            if(NRPPersonil != null) {
                UI_Insert_Anak.txt_NRP.setText(txt_NRPPersonil.getText());
                ui_insert_anak.setVisible(true);
            }
            else
            JOptionPane.showMessageDialog(null, "Pastikan NRP Personil sudah diisi dan disimpan terlebih dahulu");
        }catch(HeadlessException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_button_insert_tambah_anakActionPerformed

    private void button_insert_tambah_istriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_insert_tambah_istriActionPerformed
        String NRPPersonil = txt_NRPPersonil.getText();
        UI_Insert_Istri ui_insert_istri = new UI_Insert_Istri();

        try {
            if(NRPPersonil != null) {
                UI_Insert_Istri.txt_NRP.setText(txt_NRPPersonil.getText());
                ui_insert_istri.setVisible(true);
            }
            else
            JOptionPane.showMessageDialog(null, "Pastikan NRP Personil sudah diisi dan disimpan terlebih dahulu");
        }catch(HeadlessException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_button_insert_tambah_istriActionPerformed

    private void btnInsertPersonilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertPersonilActionPerformed
        String NRP = txt_NRPPersonil.getText();
        String agamaPersonil = combo_agamaPersonil.getSelectedItem().toString();
        String golDarahPersonil = combo_golDarahPersonil.getSelectedItem().toString();
        String jabatan = txt_jabatan.getText();
        String korps = combo_korps.getSelectedItem().toString();
        String namaPersonil = txt_namaPersonil.getText();
        String noASABRI = txt_noASABRI.getText();
        String noBPJS = txt_noBPJS.getText();
        String noKTA = txt_noKTA.getText();
        String noNPWP = txt_noNPWP.getText();
        String noTelepon = txt_noTelepon.getText();
        String pangkat = combo_pangkat.getSelectedItem().toString();
        String penMiliter = combo_pendidikanMiliter.getSelectedItem().toString();
        String penPengembang = txt_pendidikanPengembang.getText();
        String penUmum = txt_pendidikanUmum.getText();
        String statusKeluarga = txt_statusKeluarga.getText();
        String statusRumah = txt_statusRumah.getText();
        Date tamatJabatan = date_TMTJabatan.getDate();
        Date tamatTNI = date_TMTTNI.getDate();
        String tmptLahirPersonil = txt_tempatLahirPersonil.getText();
        //        DateFormat fmt = new SimpleDateFormat("dd MMMM yyyy");
        //        String tglLahirPersonil= fmt.format(this.date_tanggalLahirPersonil.getDate());
        Date tglLahirPersonil = date_tglLahirPersonil.getDate();
        Date tmtPangkatPertama = date_TMTPangkatPertama.getDate();
        Date tmtPangkatTerakhir = date_TMTPangkatTerakhir.getDate();
        String alamatPersonil = txt_alamatPersonil.getText();

        if(NRP.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Pastikan NRP Personil sudah diisi dan disimpan terlebih dahulu");
        }
        else if(agamaPersonil.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Pastikan Data sudah terisi");
        }
        else
        {
            controlMaster.InsertPersonilData(NRP, agamaPersonil, golDarahPersonil, jabatan, korps, namaPersonil, noASABRI, noBPJS,
                noKTA, noNPWP, noTelepon, pangkat, penMiliter, penPengembang, penUmum, statusKeluarga, statusRumah,
                tamatJabatan, tamatTNI, tglLahirPersonil, tmptLahirPersonil, tmtPangkatPertama, tmtPangkatTerakhir,
                alamatPersonil);
            // this.dispose();
            // UI_Utama_v2.dispose();
//            new UI_Utama_v2().setVisible(true);
        }
    }//GEN-LAST:event_btnInsertPersonilActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Insert_Personil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Insert_Personil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Insert_Personil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Insert_Personil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UI_Insert_Personil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton btnInsertPersonil;
    private javax.swing.JButton button_insert_tambah_anak;
    private javax.swing.JButton button_insert_tambah_istri;
    private javax.swing.JComboBox<String> combo_agamaPersonil;
    private javax.swing.JComboBox<String> combo_golDarahPersonil;
    private javax.swing.JComboBox<String> combo_korps;
    private javax.swing.JComboBox<String> combo_pangkat;
    private javax.swing.JComboBox<String> combo_pendidikanMiliter;
    private com.toedter.calendar.JDateChooser date_TMTJabatan;
    private com.toedter.calendar.JDateChooser date_TMTPangkatPertama;
    private com.toedter.calendar.JDateChooser date_TMTPangkatTerakhir;
    private com.toedter.calendar.JDateChooser date_TMTTNI;
    private com.toedter.calendar.JDateChooser date_tglLahirPersonil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txt_NRPPersonil;
    private javax.swing.JTextField txt_alamatPersonil;
    private javax.swing.JTextField txt_jabatan;
    private javax.swing.JTextField txt_namaPersonil;
    private javax.swing.JTextField txt_noASABRI;
    private javax.swing.JTextField txt_noBPJS;
    private javax.swing.JTextField txt_noKTA;
    private javax.swing.JTextField txt_noNPWP;
    private javax.swing.JTextField txt_noTelepon;
    private javax.swing.JTextField txt_pendidikanPengembang;
    private javax.swing.JTextField txt_pendidikanUmum;
    private javax.swing.JTextField txt_statusKeluarga;
    private javax.swing.JTextField txt_statusRumah;
    private javax.swing.JTextField txt_tempatLahirPersonil;
    // End of variables declaration//GEN-END:variables
}
